### PR TITLE
Fix vips gifs

### PR DESCRIPTION
**Pull request by jonhartzler**
gifs were not being processed by vips.  we are now converting them to pngs first.

### CODE REVIEW

**Comment by jaronkk** [comment]
Is there a reason ItemMetaDataForm.jsx is included in this?

**Comment by jonhartzler** [comment]
only that that file has had a large number of style violations and i fixed it before i started this feature (because it was bothering me) and i did not want it to be in its own request because it was just style changes.

**Comment by jgondron** [comment]
:+1:

**Comment by jaronkk** [comment]
:+1:

**Pull request merged**
